# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_underline_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnderlineActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
