# This file was auto-generated by Fern from our API Definition.

import typing

DocSignaturesList200ResponseSignaturesItemFieldMdpAction = typing.Union[
    typing.Literal["all", "include", "exclude"], typing.Any
]
