# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_highlight_actions_page_invisible_root import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_highlight_actions_page_invisible_warnings_item import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleWarningsItem,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisible(UniversalBaseModel):
    root: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleRoot] = (
        None
    )
    incomplete: bool
    warning_flags: typing_extensions.Annotated[
        int, FieldMetadata(alias="warningFlags"), pydantic.Field(alias="warningFlags")
    ]
    warnings: typing.List[
        DocAnnotationsListAll200ResponsePagesItemAnnotationsItemHighlightActionsPageInvisibleWarningsItem
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
