# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemLineIntent = typing.Union[
    typing.Literal["LineArrow", "LineDimension"], typing.Any
]
