# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_mouse_up_root_type import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsMouseUpRootType,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsMouseUpRoot(UniversalBaseModel):
    type: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsMouseUpRootType
    subtype: str
    script: typing.Optional[str] = None
    next: typing.List[typing.Any]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
