# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .doc_annotations_list200response_annotations_item_line_actions_mouse_up_root_type import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsMouseUpRootType,
)


class DocAnnotationsList200ResponseAnnotationsItemLineActionsMouseUpRoot(UniversalBaseModel):
    type: DocAnnotationsList200ResponseAnnotationsItemLineActionsMouseUpRootType
    subtype: str
    script: typing.Optional[str] = None
    next: typing.List[typing.Any]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
