# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_free_text_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
