# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleScript = (
    typing.Union[typing.Literal["normal", "sub", "super"], typing.Any]
)
