# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutIntent = typing.Union[
    typing.Literal["strikeout-text-edit"], typing.Any
]
