# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_squiggly_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquigglyActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
