# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretIntent = typing.Union[
    typing.Literal["replace"], typing.Any
]
