# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_squiggly_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsActivate,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsBlur,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsFocus,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_squiggly_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemSquigglyActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquigglyActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
