# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetFieldFamily = typing.Union[
    typing.Literal["text", "checkbox", "radio", "combobox", "listbox", "pushbutton", "signature", "unknown"], typing.Any
]
