# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_line_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsActivate,
)
from .doc_annotations_list200response_annotations_item_line_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsBlur,
)
from .doc_annotations_list200response_annotations_item_line_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_line_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_line_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsFocus,
)
from .doc_annotations_list200response_annotations_item_line_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_line_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_line_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_line_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_line_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_line_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemLineActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemLineActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLineActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
