# This file was auto-generated by Fern from our API Definition.

import typing

DocSignaturesAbort200ResponseStatus = typing.Union[
    typing.Literal["aborted", "already-completed", "unknown"], typing.Any
]
