# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIntent = typing.Union[
    typing.Literal["PolyLineDimension"], typing.Any
]
