# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_square_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemSquareActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
