# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_file_attachment_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsActivate] = (
        None
    )
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFileAttachmentActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
