# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_redact_actions_page_visible_root import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageVisibleRoot,
)
from .doc_annotations_list200response_annotations_item_redact_actions_page_visible_warnings_item import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageVisibleWarningsItem,
)


class DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageVisible(UniversalBaseModel):
    root: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageVisibleRoot] = None
    incomplete: bool
    warning_flags: typing_extensions.Annotated[
        int, FieldMetadata(alias="warningFlags"), pydantic.Field(alias="warningFlags")
    ]
    warnings: typing.List[DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageVisibleWarningsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
