# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyDir = typing.Union[
    typing.Literal["ltr", "rtl"], typing.Any
]
