# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemPolylineMeasureRlXItemLabelPosition = typing.Union[
    typing.Literal["suffix", "prefix"], typing.Any
]
