# This file was auto-generated by Fern from our API Definition.

import typing

DocSignaturesAnalysis200ResponseVerdict = typing.Union[
    typing.Literal["unchanged", "permitted", "forbidden", "indeterminate"], typing.Any
]
