# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemLineMeasureRlYItemFraction = typing.Union[
    typing.Literal["decimal", "fraction", "round", "truncate"], typing.Any
]
