# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_widget_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
