# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_file_attachment_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsActivate,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsBlur,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsFocus,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_file_attachment_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemFileAttachmentActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
