# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemPolylineLineEndingsEnd = typing.Union[
    typing.Literal[
        "none",
        "square",
        "circle",
        "diamond",
        "open-arrow",
        "closed-arrow",
        "butt",
        "r-open-arrow",
        "r-closed-arrow",
        "slash",
    ],
    typing.Any,
]
