# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineCaptionPosition = typing.Union[
    typing.Literal["inline", "top"], typing.Any
]
