# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_underline_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsActivate,
)
from .doc_annotations_list200response_annotations_item_underline_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsBlur,
)
from .doc_annotations_list200response_annotations_item_underline_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_underline_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_underline_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsFocus,
)
from .doc_annotations_list200response_annotations_item_underline_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_underline_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_underline_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_underline_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_underline_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_underline_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemUnderlineActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnderlineActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
