# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_update200response_meta_affected_pages_item_revision import (
    DocAnnotationsUpdate200ResponseMetaAffectedPagesItemRevision,
)
from .doc_annotations_update200response_meta_affected_pages_item_weak_annotation_state import (
    DocAnnotationsUpdate200ResponseMetaAffectedPagesItemWeakAnnotationState,
)


class DocAnnotationsUpdate200ResponseMetaAffectedPagesItem(UniversalBaseModel):
    page_object_number: typing_extensions.Annotated[
        int, FieldMetadata(alias="pageObjectNumber"), pydantic.Field(alias="pageObjectNumber")
    ]
    revision: DocAnnotationsUpdate200ResponseMetaAffectedPagesItemRevision
    weak_annotation_state: typing_extensions.Annotated[
        DocAnnotationsUpdate200ResponseMetaAffectedPagesItemWeakAnnotationState,
        FieldMetadata(alias="weakAnnotationState"),
        pydantic.Field(alias="weakAnnotationState"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
