# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineIdentityQuality = typing.Union[
    typing.Literal["durable", "weak"], typing.Any
]
