# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemTextIcon = typing.Union[
    typing.Literal["comment", "key", "note", "help", "new-paragraph", "paragraph", "insert"], typing.Any
]
