# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineIntent = typing.Union[
    typing.Literal["LineArrow", "LineDimension"], typing.Any
]
