# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemCircleBorderStyle = typing.Union[
    typing.Literal["solid", "dashed", "beveled", "inset"], typing.Any
]
