# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_polygon_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsActivate,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsBlur,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsFocus,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_polygon_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemPolygonActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemPolygonActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
