# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageCloseRootType = typing.Union[
    typing.Literal[
        "unknown",
        "goto",
        "goto-remote",
        "goto-embedded",
        "launch",
        "thread",
        "uri",
        "sound",
        "movie",
        "hide",
        "named",
        "submit-form",
        "reset-form",
        "import-data",
        "javascript",
        "set-ocg-state",
        "rendition",
        "transition",
        "goto-3d-view",
    ],
    typing.Any,
]
