# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_redact_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemRedactActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
