# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_strikeout_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStrikeoutActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
