# This file was auto-generated by Fern from our API Definition.

import typing

DocVersionsSignatures200ResponseProtectionJudged = typing.Union[
    typing.Literal["none", "lta", "fill", "annotate"], typing.Any
]
