# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_unsupported_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsActivate,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsBlur,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsFocus,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_unsupported_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemUnsupportedActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemUnsupportedActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
