# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampReplyType = typing.Union[
    typing.Literal["reply", "group"], typing.Any
]
