# This file was auto-generated by Fern from our API Definition.

import typing

DocVersionsAnalysis200ResponseCurrentFindingsItemVerdict = typing.Union[
    typing.Literal["permitted", "forbidden", "incomplete"], typing.Any
]
