# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_strikeout_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsActivate,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsBlur,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsFocus,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_strikeout_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemStrikeoutActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStrikeoutActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
