# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemAlign = typing.Union[
    typing.Literal["left", "center", "right", "justify"], typing.Any
]
