# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_circle_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCircleActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
