# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolylineMeasureRlYItemLabelPosition = typing.Union[
    typing.Literal["suffix", "prefix"], typing.Any
]
