# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemPolygonIntent = typing.Union[
    typing.Literal["PolygonCloud", "PolygonDimension"], typing.Any
]
