# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_forms_get200response_fields_item_text_actions_calculate import (
    DocFormsGet200ResponseFieldsItemTextActionsCalculate,
)
from .doc_forms_get200response_fields_item_text_actions_format import DocFormsGet200ResponseFieldsItemTextActionsFormat
from .doc_forms_get200response_fields_item_text_actions_keystroke import (
    DocFormsGet200ResponseFieldsItemTextActionsKeystroke,
)
from .doc_forms_get200response_fields_item_text_actions_validate import (
    DocFormsGet200ResponseFieldsItemTextActionsValidate,
)


class DocFormsGet200ResponseFieldsItemTextActions(UniversalBaseModel):
    keystroke: typing.Optional[DocFormsGet200ResponseFieldsItemTextActionsKeystroke] = None
    format: typing.Optional[DocFormsGet200ResponseFieldsItemTextActionsFormat] = None
    validate_: typing_extensions.Annotated[
        typing.Optional[DocFormsGet200ResponseFieldsItemTextActionsValidate],
        FieldMetadata(alias="validate"),
        pydantic.Field(alias="validate"),
    ] = None
    calculate: typing.Optional[DocFormsGet200ResponseFieldsItemTextActionsCalculate] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
