# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemInkIdentityQuality = typing.Union[
    typing.Literal["durable", "weak"], typing.Any
]
