# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_stamp_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemStampActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
