# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextBodyScript = typing.Union[
    typing.Literal["normal", "sub", "super"], typing.Any
]
