# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_page_state_revision import DocAnnotationsList200ResponsePageStateRevision
from .doc_annotations_list200response_page_state_weak_annotation_state import (
    DocAnnotationsList200ResponsePageStateWeakAnnotationState,
)


class DocAnnotationsList200ResponsePageState(UniversalBaseModel):
    page_object_number: typing_extensions.Annotated[
        int, FieldMetadata(alias="pageObjectNumber"), pydantic.Field(alias="pageObjectNumber")
    ]
    revision: DocAnnotationsList200ResponsePageStateRevision
    weak_annotation_state: typing_extensions.Annotated[
        DocAnnotationsList200ResponsePageStateWeakAnnotationState,
        FieldMetadata(alias="weakAnnotationState"),
        pydantic.Field(alias="weakAnnotationState"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
