# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemRedactTextAlign = typing.Union[
    typing.Literal["left", "center", "right"], typing.Any
]
