# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .doc_annotations_list_all200response_pages_item_annotations_item_link_target_goto_destination import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetGotoDestination,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetGoto(UniversalBaseModel):
    destination: DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkTargetGotoDestination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
