# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemFreeTextIntent = typing.Union[
    typing.Literal["free-text", "free-text-callout"], typing.Any
]
