# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_blur_root import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_blur_warnings_item import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurWarningsItem,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlur(UniversalBaseModel):
    root: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurRoot] = None
    incomplete: bool
    warning_flags: typing_extensions.Annotated[
        int, FieldMetadata(alias="warningFlags"), pydantic.Field(alias="warningFlags")
    ]
    warnings: typing.List[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlurWarningsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
