# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineMeasureRlAreaItemFraction = typing.Union[
    typing.Literal["decimal", "fraction", "round", "truncate"], typing.Any
]
