# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemWidgetActionsCursorExitWarningsItem = typing.Union[
    typing.Literal["cycle-dropped", "malformed-next", "incomplete"], typing.Any
]
