# This file was auto-generated by Fern from our API Definition.

import typing

DocVersionsSignatures200ResponseSignaturesItemKind = typing.Union[typing.Literal["signature", "timestamp"], typing.Any]
