# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemPolylineIntent = typing.Union[
    typing.Literal["PolyLineDimension"], typing.Any
]
