# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemPolygonReplyType = typing.Union[
    typing.Literal["reply", "group"], typing.Any
]
