# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_square_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsActivate,
)
from .doc_annotations_list200response_annotations_item_square_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsBlur,
)
from .doc_annotations_list200response_annotations_item_square_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_square_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_square_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsFocus,
)
from .doc_annotations_list200response_annotations_item_square_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_square_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_square_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_square_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_square_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_square_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemSquareActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemSquareActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
