# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_circle_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsActivate,
)
from .doc_annotations_list200response_annotations_item_circle_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsBlur,
)
from .doc_annotations_list200response_annotations_item_circle_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_circle_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_circle_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsFocus,
)
from .doc_annotations_list200response_annotations_item_circle_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_circle_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_circle_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_circle_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_circle_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_circle_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemCircleActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemCircleActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCircleActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
