# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_link_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLinkActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
