# This file was auto-generated by Fern from our API Definition.

import typing

DocSignaturesList200ResponseSignaturesItemCoverage = typing.Union[
    typing.Literal["whole-revision", "partial", "malformed"], typing.Any
]
