# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_caret_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemCaretActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
