# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_stamp_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsActivate,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsBlur,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsFocus,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_stamp_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemStampActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemStampActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemStampActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
