# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemFileAttachmentIcon = typing.Union[
    typing.Literal["push-pin", "paperclip", "graph", "tag"], typing.Any
]
