# This file was auto-generated by Fern from our API Definition.

import typing

DocHead200ResponseEncryptionState = typing.Union[
    typing.Literal["unknown", "none", "encrypted", "unsupported"], typing.Any
]
