# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_forms_get200response_fields_item_signature_actions_calculate import (
    DocFormsGet200ResponseFieldsItemSignatureActionsCalculate,
)
from .doc_forms_get200response_fields_item_signature_actions_format import (
    DocFormsGet200ResponseFieldsItemSignatureActionsFormat,
)
from .doc_forms_get200response_fields_item_signature_actions_keystroke import (
    DocFormsGet200ResponseFieldsItemSignatureActionsKeystroke,
)
from .doc_forms_get200response_fields_item_signature_actions_validate import (
    DocFormsGet200ResponseFieldsItemSignatureActionsValidate,
)


class DocFormsGet200ResponseFieldsItemSignatureActions(UniversalBaseModel):
    keystroke: typing.Optional[DocFormsGet200ResponseFieldsItemSignatureActionsKeystroke] = None
    format: typing.Optional[DocFormsGet200ResponseFieldsItemSignatureActionsFormat] = None
    validate_: typing_extensions.Annotated[
        typing.Optional[DocFormsGet200ResponseFieldsItemSignatureActionsValidate],
        FieldMetadata(alias="validate"),
        pydantic.Field(alias="validate"),
    ] = None
    calculate: typing.Optional[DocFormsGet200ResponseFieldsItemSignatureActionsCalculate] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
