# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemFreeTextRichTextParagraphsItemDir = typing.Union[
    typing.Literal["ltr", "rtl"], typing.Any
]
