# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_widget_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivate,
)
from .doc_annotations_list200response_annotations_item_widget_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsBlur,
)
from .doc_annotations_list200response_annotations_item_widget_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_widget_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_widget_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocus,
)
from .doc_annotations_list200response_annotations_item_widget_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_widget_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_widget_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_widget_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_widget_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_widget_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemWidgetActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemWidgetActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemWidgetActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
