# This file was auto-generated by Fern from our API Definition.

import typing

from .doc_pages_viewports200response_item import DocPagesViewports200ResponseItem

DocPagesViewports200Response = typing.List[DocPagesViewports200ResponseItem]
