# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_forms_get200response_fields_item_combobox_actions_validate_root import (
    DocFormsGet200ResponseFieldsItemComboboxActionsValidateRoot,
)
from .doc_forms_get200response_fields_item_combobox_actions_validate_warnings_item import (
    DocFormsGet200ResponseFieldsItemComboboxActionsValidateWarningsItem,
)


class DocFormsGet200ResponseFieldsItemComboboxActionsValidate(UniversalBaseModel):
    root: typing.Optional[DocFormsGet200ResponseFieldsItemComboboxActionsValidateRoot] = None
    incomplete: bool
    warning_flags: typing_extensions.Annotated[
        int, FieldMetadata(alias="warningFlags"), pydantic.Field(alias="warningFlags")
    ]
    warnings: typing.List[DocFormsGet200ResponseFieldsItemComboboxActionsValidateWarningsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
