# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_text_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemTextActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
