# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsList200ResponseAnnotationsItemLineCaptionPosition = typing.Union[
    typing.Literal["inline", "top"], typing.Any
]
