# This file was auto-generated by Fern from our API Definition.

import typing

DocAnnotationsListAll200ResponsePagesItemAnnotationsItemFreeTextRichTextParagraphsItemRunsItemStyleDecorationItem = (
    typing.Union[typing.Literal["underline", "line-through", "word"], typing.Any]
)
