# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_redact_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsActivate,
)
from .doc_annotations_list200response_annotations_item_redact_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsBlur,
)
from .doc_annotations_list200response_annotations_item_redact_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_redact_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_redact_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsFocus,
)
from .doc_annotations_list200response_annotations_item_redact_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_redact_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_redact_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_redact_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_redact_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_redact_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemRedactActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemRedactActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
