# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_forms_get200response_fields_item_listbox_actions_calculate import (
    DocFormsGet200ResponseFieldsItemListboxActionsCalculate,
)
from .doc_forms_get200response_fields_item_listbox_actions_format import (
    DocFormsGet200ResponseFieldsItemListboxActionsFormat,
)
from .doc_forms_get200response_fields_item_listbox_actions_keystroke import (
    DocFormsGet200ResponseFieldsItemListboxActionsKeystroke,
)
from .doc_forms_get200response_fields_item_listbox_actions_validate import (
    DocFormsGet200ResponseFieldsItemListboxActionsValidate,
)


class DocFormsGet200ResponseFieldsItemListboxActions(UniversalBaseModel):
    keystroke: typing.Optional[DocFormsGet200ResponseFieldsItemListboxActionsKeystroke] = None
    format: typing.Optional[DocFormsGet200ResponseFieldsItemListboxActionsFormat] = None
    validate_: typing_extensions.Annotated[
        typing.Optional[DocFormsGet200ResponseFieldsItemListboxActionsValidate],
        FieldMetadata(alias="validate"),
        pydantic.Field(alias="validate"),
    ] = None
    calculate: typing.Optional[DocFormsGet200ResponseFieldsItemListboxActionsCalculate] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
