# This file was auto-generated by Fern from our API Definition.

import typing

DocHead200ResponseAccessReasonsItem = typing.Union[typing.Literal["password", "cdn", "permissions-unknown"], typing.Any]
