# This file was auto-generated by Fern from our API Definition.

import typing

DocSignaturesAnalysis200ResponseCurrentMethod = typing.Union[
    typing.Literal["net-state", "net-state+replay"], typing.Any
]
