# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .doc_forms_get200response_fields_item_pushbutton_actions_validate_root_type import (
    DocFormsGet200ResponseFieldsItemPushbuttonActionsValidateRootType,
)


class DocFormsGet200ResponseFieldsItemPushbuttonActionsValidateRoot(UniversalBaseModel):
    type: DocFormsGet200ResponseFieldsItemPushbuttonActionsValidateRootType
    subtype: str
    script: typing.Optional[str] = None
    next: typing.List[typing.Any]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
