# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_link_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsActivate,
)
from .doc_annotations_list200response_annotations_item_link_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsBlur,
)
from .doc_annotations_list200response_annotations_item_link_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_link_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_link_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsFocus,
)
from .doc_annotations_list200response_annotations_item_link_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_link_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_link_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_link_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_link_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_link_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemLinkActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemLinkActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
