# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_text_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsActivate,
)
from .doc_annotations_list200response_annotations_item_text_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsBlur,
)
from .doc_annotations_list200response_annotations_item_text_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_text_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_text_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsFocus,
)
from .doc_annotations_list200response_annotations_item_text_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_text_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_text_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_text_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_text_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_text_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemTextActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemTextActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemTextActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
