# This file was auto-generated by Fern from our API Definition.

import typing

DocPagesViewports200ResponseItemMeasureRlAngleItemLabelPosition = typing.Union[
    typing.Literal["suffix", "prefix"], typing.Any
]
