# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_line_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemLineActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
