# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_forms_import_data200response_meta_cache_delta_pages_item import (
    DocFormsImportData200ResponseMetaCacheDeltaPagesItem,
)


class DocFormsImportData200ResponseMetaCacheDelta(UniversalBaseModel):
    previous_doc_version: typing_extensions.Annotated[
        int, FieldMetadata(alias="previousDocVersion"), pydantic.Field(alias="previousDocVersion")
    ]
    doc_version: typing_extensions.Annotated[int, FieldMetadata(alias="docVersion"), pydantic.Field(alias="docVersion")]
    pages: typing.List[DocFormsImportData200ResponseMetaCacheDeltaPagesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
