# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_activate import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsActivate,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_blur import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlur,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_cursor_enter import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsCursorEnter,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_cursor_exit import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsCursorExit,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_focus import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsFocus,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_mouse_down import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsMouseDown,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_mouse_up import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsMouseUp,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_page_close import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsPageClose,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_page_invisible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsPageInvisible,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_page_open import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsPageOpen,
)
from .doc_annotations_list_all200response_pages_item_annotations_item_unsupported_actions_page_visible import (
    DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsPageVisible,
)


class DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsFocus] = None
    blur: typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsListAll200ResponsePagesItemAnnotationsItemUnsupportedActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
