# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_caret_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivate,
)
from .doc_annotations_list200response_annotations_item_caret_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsBlur,
)
from .doc_annotations_list200response_annotations_item_caret_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_caret_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_caret_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsFocus,
)
from .doc_annotations_list200response_annotations_item_caret_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_caret_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_caret_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_caret_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_caret_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_caret_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemCaretActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemCaretActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemCaretActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
