# This file was auto-generated by Fern from our API Definition.

import typing

DocPagesDelete404ResponseCode = typing.Union[
    typing.Literal[
        "Unknown",
        "InvalidArg",
        "DocNotOpen",
        "DocOpenFailed",
        "DocPasswordRequired",
        "DocPasswordIncorrect",
        "Aborted",
        "Network",
        "Unauthenticated",
        "Forbidden",
        "NotFound",
        "WireFormat",
        "RuntimeUnavailable",
        "InvalidReference",
        "WeakAnnotationSessionConflict",
        "LayerVersionConflict",
        "NotImplemented",
        "MalformedPdf",
    ],
    typing.Any,
]
