# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_annotations_list200response_annotations_item_ink_actions_activate import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsActivate,
)
from .doc_annotations_list200response_annotations_item_ink_actions_blur import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsBlur,
)
from .doc_annotations_list200response_annotations_item_ink_actions_cursor_enter import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsCursorEnter,
)
from .doc_annotations_list200response_annotations_item_ink_actions_cursor_exit import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsCursorExit,
)
from .doc_annotations_list200response_annotations_item_ink_actions_focus import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsFocus,
)
from .doc_annotations_list200response_annotations_item_ink_actions_mouse_down import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsMouseDown,
)
from .doc_annotations_list200response_annotations_item_ink_actions_mouse_up import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsMouseUp,
)
from .doc_annotations_list200response_annotations_item_ink_actions_page_close import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsPageClose,
)
from .doc_annotations_list200response_annotations_item_ink_actions_page_invisible import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsPageInvisible,
)
from .doc_annotations_list200response_annotations_item_ink_actions_page_open import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsPageOpen,
)
from .doc_annotations_list200response_annotations_item_ink_actions_page_visible import (
    DocAnnotationsList200ResponseAnnotationsItemInkActionsPageVisible,
)


class DocAnnotationsList200ResponseAnnotationsItemInkActions(UniversalBaseModel):
    activate: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsActivate] = None
    cursor_enter: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsCursorEnter],
        FieldMetadata(alias="cursorEnter"),
        pydantic.Field(alias="cursorEnter"),
    ] = None
    cursor_exit: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsCursorExit],
        FieldMetadata(alias="cursorExit"),
        pydantic.Field(alias="cursorExit"),
    ] = None
    mouse_down: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsMouseDown],
        FieldMetadata(alias="mouseDown"),
        pydantic.Field(alias="mouseDown"),
    ] = None
    mouse_up: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsMouseUp],
        FieldMetadata(alias="mouseUp"),
        pydantic.Field(alias="mouseUp"),
    ] = None
    focus: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsFocus] = None
    blur: typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsBlur] = None
    page_open: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsPageOpen],
        FieldMetadata(alias="pageOpen"),
        pydantic.Field(alias="pageOpen"),
    ] = None
    page_close: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsPageClose],
        FieldMetadata(alias="pageClose"),
        pydantic.Field(alias="pageClose"),
    ] = None
    page_visible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsPageVisible],
        FieldMetadata(alias="pageVisible"),
        pydantic.Field(alias="pageVisible"),
    ] = None
    page_invisible: typing_extensions.Annotated[
        typing.Optional[DocAnnotationsList200ResponseAnnotationsItemInkActionsPageInvisible],
        FieldMetadata(alias="pageInvisible"),
        pydantic.Field(alias="pageInvisible"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
