# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .doc_forms_get200response_fields_item_text_actions_keystroke_root import (
    DocFormsGet200ResponseFieldsItemTextActionsKeystrokeRoot,
)
from .doc_forms_get200response_fields_item_text_actions_keystroke_warnings_item import (
    DocFormsGet200ResponseFieldsItemTextActionsKeystrokeWarningsItem,
)


class DocFormsGet200ResponseFieldsItemTextActionsKeystroke(UniversalBaseModel):
    root: typing.Optional[DocFormsGet200ResponseFieldsItemTextActionsKeystrokeRoot] = None
    incomplete: bool
    warning_flags: typing_extensions.Annotated[
        int, FieldMetadata(alias="warningFlags"), pydantic.Field(alias="warningFlags")
    ]
    warnings: typing.List[DocFormsGet200ResponseFieldsItemTextActionsKeystrokeWarningsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
