# This file was auto-generated by Fern from our API Definition.

import typing

DocumentsInit200ResponseResumedDocumentState = typing.Union[
    typing.Literal["pending", "ready", "failed", "deleting"], typing.Any
]
