# This file was auto-generated by Fern from our API Definition.

import typing

DocumentsCommit200ResponseDocumentState = typing.Union[
    typing.Literal["pending", "ready", "failed", "deleting"], typing.Any
]
