# This file was auto-generated by Fern from our API Definition.

import typing

DocumentsInit200ResponseResumedDocumentThumbnailState = typing.Union[
    typing.Literal["pending", "ready", "locked", "failed"], typing.Any
]
