# This file was auto-generated by Fern from our API Definition.

import typing

PdfActionTreeWarningsItem = typing.Union[
    typing.Literal["cycle-dropped", "malformed-next", "incomplete", "payload-dropped"], typing.Any
]
