# This file was auto-generated by Fern from our API Definition.

import typing

from .tokens_issue_request_tenant_scope_item_one import TokensIssueRequestTenantScopeItemOne
from .tokens_issue_request_tenant_scope_item_zero import TokensIssueRequestTenantScopeItemZero

TokensIssueRequestTenantScopeItem = typing.Union[
    TokensIssueRequestTenantScopeItemZero, TokensIssueRequestTenantScopeItemOne
]
