# This file was auto-generated by Fern from our API Definition.

import typing

TokensIssueRequestTenantScopeItemOne = typing.Union[
    typing.Literal["docs.create", "docs.read", "docs.delete", "tokens.issue-doc", "tokens.revoke"], typing.Any
]
