# This file was auto-generated by Fern from our API Definition.

import typing

SignatureDigestVersionsRequestAlgorithm = typing.Union[typing.Literal["sha1", "sha256", "sha384", "sha512"], typing.Any]
