# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.tenants_create200response import TenantsCreate200Response
from ..types.tenants_get200response import TenantsGet200Response
from ..types.tenants_list200response import TenantsList200Response
from .raw_client import AsyncRawTenantsClient, RawTenantsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TenantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTenantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTenantsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TenantsList200Response:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantsList200Response
            OK

        Examples
        --------
        from cloudpdf import CloudPDFClient

        client = CloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tenants.list()
        """
        _response = self._raw_client.list(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def create(
        self, *, id: str, name: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> TenantsCreate200Response:
        """
        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantsCreate200Response
            OK

        Examples
        --------
        from cloudpdf import CloudPDFClient

        client = CloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tenants.create(
            id="id",
        )
        """
        _response = self._raw_client.create(id=id, name=name, request_options=request_options)
        return _response.data

    def get(self, tenant_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> TenantsGet200Response:
        """
        Parameters
        ----------
        tenant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantsGet200Response
            OK

        Examples
        --------
        from cloudpdf import CloudPDFClient

        client = CloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tenants.get(
            tenant_id="tenantId",
        )
        """
        _response = self._raw_client.get(tenant_id, request_options=request_options)
        return _response.data

    def delete(self, tenant_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Destroys the tenant and everything in its namespace — documents, layers, stored bytes, audit history. Irreversible.

        Parameters
        ----------
        tenant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from cloudpdf import CloudPDFClient

        client = CloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.tenants.delete(
            tenant_id="tenantId",
        )
        """
        _response = self._raw_client.delete(tenant_id, request_options=request_options)
        return _response.data


class AsyncTenantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTenantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTenantsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TenantsList200Response:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        cursor : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantsList200Response
            OK

        Examples
        --------
        import asyncio

        from cloudpdf import AsyncCloudPDFClient

        client = AsyncCloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tenants.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    async def create(
        self, *, id: str, name: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> TenantsCreate200Response:
        """
        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantsCreate200Response
            OK

        Examples
        --------
        import asyncio

        from cloudpdf import AsyncCloudPDFClient

        client = AsyncCloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tenants.create(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(id=id, name=name, request_options=request_options)
        return _response.data

    async def get(
        self, tenant_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> TenantsGet200Response:
        """
        Parameters
        ----------
        tenant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TenantsGet200Response
            OK

        Examples
        --------
        import asyncio

        from cloudpdf import AsyncCloudPDFClient

        client = AsyncCloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tenants.get(
                tenant_id="tenantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(tenant_id, request_options=request_options)
        return _response.data

    async def delete(self, tenant_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Destroys the tenant and everything in its namespace — documents, layers, stored bytes, audit history. Irreversible.

        Parameters
        ----------
        tenant_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from cloudpdf import AsyncCloudPDFClient

        client = AsyncCloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.tenants.delete(
                tenant_id="tenantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(tenant_id, request_options=request_options)
        return _response.data
