# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.doc_annotations_create200response import DocAnnotationsCreate200Response
from ...types.doc_annotations_create_request import DocAnnotationsCreateRequest
from ...types.doc_annotations_delete200response import DocAnnotationsDelete200Response
from ...types.doc_annotations_list200response import DocAnnotationsList200Response
from ...types.doc_annotations_update200response import DocAnnotationsUpdate200Response
from ...types.doc_annotations_update_request import DocAnnotationsUpdateRequest
from .raw_client import AsyncRawAnnotationsClient, RawAnnotationsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AnnotationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAnnotationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAnnotationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAnnotationsClient
        """
        return self._raw_client

    def list(
        self,
        doc_id: str,
        layer_name: str,
        pon: int,
        *,
        document_password: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocAnnotationsList200Response:
        """
        Parameters
        ----------
        doc_id : str

        layer_name : str

        pon : int

        document_password : typing.Optional[str]
            Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocAnnotationsList200Response
            OK

        Examples
        --------
        from cloudpdf import CloudPDFClient

        client = CloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.doc.annotations.list(
            doc_id="docId",
            layer_name="layerName",
            pon=1,
        )
        """
        _response = self._raw_client.list(
            doc_id, layer_name, pon, document_password=document_password, request_options=request_options
        )
        return _response.data

    def create(
        self,
        doc_id: str,
        layer_name: str,
        pon: int,
        *,
        request: DocAnnotationsCreateRequest,
        document_password: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocAnnotationsCreate200Response:
        """
        Doc JWTs may instead carry collab scopes (annotations:create:self, …) that refine per-annotation authorship rules; the API token is exempt from both.

        Parameters
        ----------
        doc_id : str

        layer_name : str

        pon : int

        request : DocAnnotationsCreateRequest

        document_password : typing.Optional[str]
            Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocAnnotationsCreate200Response
            OK

        Examples
        --------
        from cloudpdf import CloudPDFClient

        client = CloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.doc.annotations.create(
            doc_id="docId",
            layer_name="layerName",
            pon=1,
            request={"key": "value"},
        )
        """
        _response = self._raw_client.create(
            doc_id,
            layer_name,
            pon,
            request=request,
            document_password=document_password,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self,
        doc_id: str,
        layer_name: str,
        pon: int,
        annot_key: str,
        *,
        document_password: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocAnnotationsDelete200Response:
        """
        Parameters
        ----------
        doc_id : str

        layer_name : str

        pon : int

        annot_key : str

        document_password : typing.Optional[str]
            Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocAnnotationsDelete200Response
            OK

        Examples
        --------
        from cloudpdf import CloudPDFClient

        client = CloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.doc.annotations.delete(
            doc_id="docId",
            layer_name="layerName",
            pon=1,
            annot_key="annotKey",
        )
        """
        _response = self._raw_client.delete(
            doc_id, layer_name, pon, annot_key, document_password=document_password, request_options=request_options
        )
        return _response.data

    def update(
        self,
        doc_id: str,
        layer_name: str,
        pon: int,
        annot_key: str,
        *,
        request: DocAnnotationsUpdateRequest,
        document_password: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocAnnotationsUpdate200Response:
        """
        Parameters
        ----------
        doc_id : str

        layer_name : str

        pon : int

        annot_key : str

        request : DocAnnotationsUpdateRequest

        document_password : typing.Optional[str]
            Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocAnnotationsUpdate200Response
            OK

        Examples
        --------
        from cloudpdf import CloudPDFClient

        client = CloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.doc.annotations.update(
            doc_id="docId",
            layer_name="layerName",
            pon=1,
            annot_key="annotKey",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.update(
            doc_id,
            layer_name,
            pon,
            annot_key,
            request=request,
            document_password=document_password,
            request_options=request_options,
        )
        return _response.data


class AsyncAnnotationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAnnotationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAnnotationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAnnotationsClient
        """
        return self._raw_client

    async def list(
        self,
        doc_id: str,
        layer_name: str,
        pon: int,
        *,
        document_password: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocAnnotationsList200Response:
        """
        Parameters
        ----------
        doc_id : str

        layer_name : str

        pon : int

        document_password : typing.Optional[str]
            Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocAnnotationsList200Response
            OK

        Examples
        --------
        import asyncio

        from cloudpdf import AsyncCloudPDFClient

        client = AsyncCloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.doc.annotations.list(
                doc_id="docId",
                layer_name="layerName",
                pon=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            doc_id, layer_name, pon, document_password=document_password, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        doc_id: str,
        layer_name: str,
        pon: int,
        *,
        request: DocAnnotationsCreateRequest,
        document_password: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocAnnotationsCreate200Response:
        """
        Doc JWTs may instead carry collab scopes (annotations:create:self, …) that refine per-annotation authorship rules; the API token is exempt from both.

        Parameters
        ----------
        doc_id : str

        layer_name : str

        pon : int

        request : DocAnnotationsCreateRequest

        document_password : typing.Optional[str]
            Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocAnnotationsCreate200Response
            OK

        Examples
        --------
        import asyncio

        from cloudpdf import AsyncCloudPDFClient

        client = AsyncCloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.doc.annotations.create(
                doc_id="docId",
                layer_name="layerName",
                pon=1,
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            doc_id,
            layer_name,
            pon,
            request=request,
            document_password=document_password,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self,
        doc_id: str,
        layer_name: str,
        pon: int,
        annot_key: str,
        *,
        document_password: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocAnnotationsDelete200Response:
        """
        Parameters
        ----------
        doc_id : str

        layer_name : str

        pon : int

        annot_key : str

        document_password : typing.Optional[str]
            Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocAnnotationsDelete200Response
            OK

        Examples
        --------
        import asyncio

        from cloudpdf import AsyncCloudPDFClient

        client = AsyncCloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.doc.annotations.delete(
                doc_id="docId",
                layer_name="layerName",
                pon=1,
                annot_key="annotKey",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            doc_id, layer_name, pon, annot_key, document_password=document_password, request_options=request_options
        )
        return _response.data

    async def update(
        self,
        doc_id: str,
        layer_name: str,
        pon: int,
        annot_key: str,
        *,
        request: DocAnnotationsUpdateRequest,
        document_password: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DocAnnotationsUpdate200Response:
        """
        Parameters
        ----------
        doc_id : str

        layer_name : str

        pon : int

        annot_key : str

        request : DocAnnotationsUpdateRequest

        document_password : typing.Optional[str]
            Base64-encoded password for an encrypted document. Valid only with the API token (403 anywhere else). An encrypted document answers 422 DocPasswordRequired when the header is absent. Viewer doc JWTs use the SDK password-session flow instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocAnnotationsUpdate200Response
            OK

        Examples
        --------
        import asyncio

        from cloudpdf import AsyncCloudPDFClient

        client = AsyncCloudPDFClient(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.doc.annotations.update(
                doc_id="docId",
                layer_name="layerName",
                pon=1,
                annot_key="annotKey",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            doc_id,
            layer_name,
            pon,
            annot_key,
            request=request,
            document_password=document_password,
            request_options=request_options,
        )
        return _response.data
