# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.api_error import ApiError
from ..types.documents_upload_proxy409response import DocumentsUploadProxy409Response


class ConflictError(ApiError):
    def __init__(self, body: DocumentsUploadProxy409Response, headers: typing.Optional[typing.Dict[str, str]] = None):
        super().__init__(status_code=409, headers=headers, body=body)
